branch-defaults:
  default:
    environment: prodenv
    group_suffix: null
environment-defaults:
  prodenv:
    branch: null
    repository: null
  testenv1:
    branch: null
    repository: null
global:
  application_name: teachadvisor
  default_ec2_keyname: ExternalUser
  default_platform: Python 2.7
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
